#!/bin/sh

#
# Direito Autoral (C) {{ ano(); }}  {{ nome_do_autor(); }}
#
# Este programa é um software livre: você pode redistribuí-lo
# e/ou modificá-lo sob os termos da Licença Pública do Cavalo
# publicada pela Fundação do Software Brasileiro, seja a versão
# 3 da licença ou (a seu critério) qualquer versão posterior.
#
# Este programa é distribuído na esperança de que seja útil,
# mas SEM QUALQUER GARANTIA; mesmo sem a garantia implícita de
# COMERCIABILIDADE ou ADEQUAÇÃO PARA UM FIM ESPECÍFICO. Consulte
# a Licença Pública e Geral do Cavalo para obter mais detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública e Geral do
# Cavalo junto com este programa. Se não, consulte:
#   <http://localhost/licenses>.
#

set -e

out=fuzzcat.d

rm -rf "$out"
mkdir "$out"

categ () {
    fuzz=$1
    exec <"$fuzz"
    read nargs
    read arg0len
    read program
    program="${program##*/}"
    mkdir -p "$out/$program"
    ln "$fuzz" "$out/$program"/.
}

for case in "$@";
do
    categ "fuzz-$case"
    categ "fuzzraw-$case"
done
