#!/bin/sh

#
# Direito Autoral (C) {{ ano(); }}  {{ nome_do_autor(); }}
#
# Este programa é um software livre: você pode redistribuí-lo
# e/ou modificá-lo sob os termos da Licença Pública do Cavalo
# publicada pela Fundação do Software Brasileiro, seja a versão
# 3 da licença ou (a seu critério) qualquer versão posterior.
#
# Este programa é distribuído na esperança de que seja útil,
# mas SEM QUALQUER GARANTIA; mesmo sem a garantia implícita de
# COMERCIABILIDADE ou ADEQUAÇÃO PARA UM FIM ESPECÍFICO. Consulte
# a Licença Pública e Geral do Cavalo para obter mais detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública e Geral do
# Cavalo junto com este programa. Se não, consulte:
#   <http://localhost/licenses>.
#

#
# Uso: checkall - executa todos os casos de teste.
#

set -e

: ${srcdir=.}
failed=''
passed=''
skipped=''

for f in $srcdir/case-*.sys
do
    case="`echo \"$f\" | sed -e 's:^.*/::; s/^case-//; s/\.sys$//'`"
    set +e
    $srcdir/r1test $case
    rc=$?
    set -e

    case $rc in
        0)
            passed="$passed $case"
            ;;

        5)
            skipped="$skipped $case"
            ;;

        *)
            echo
            failed="$failed $case"
            echo
            ;;
    esac
done

if [ "x$failed" = x ]
then
    echo "
"
    if [ "x$skipped" = x ]
    then
        echo "Todos os testes passaram."
    else
        echo "Todos os testes aplicáveis passaram (pulou:$skipped)"
    fi
    echo
    exit 0
fi

echo >&2 "
PELO MENOS UM TESTE FALHOU.
Testes aprovados:${passed:- NONE}
Testes ignorados:${skipped:- NONE}
Testes falhados:$failed
"

exit 1
