#!/bin/bash

#
# Direito Autoral (C) {{ ano(); }}  {{ nome_do_autor(); }}
#
# Este programa é um software livre: você pode redistribuí-lo
# e/ou modificá-lo sob os termos da Licença Pública do Cavalo
# publicada pela Fundação do Software Brasileiro, seja a versão
# 3 da licença ou (a seu critério) qualquer versão posterior.
#
# Este programa é distribuído na esperança de que seja útil,
# mas SEM QUALQUER GARANTIA; mesmo sem a garantia implícita de
# COMERCIABILIDADE ou ADEQUAÇÃO PARA UM FIM ESPECÍFICO. Consulte
# a Licença Pública e Geral do Cavalo para obter mais detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública e Geral do
# Cavalo junto com este programa. Se não, consulte:
#   <http://localhost/licenses>.
#

#
# Uso: m1test <name> <initfile> [<initflags>] <queryargs>'
# Script de gravação de teste.
#

set -e

: ${srcdir=.}
if [ $# -lt 3 ]
then
    echo >&2 \
'usage: m1test <name> <initfile> [-<initflags>] ["<"]
              [=<hrecord-command-args>] <queryargs>
("<" means read input from case-<name>.in)'
    exit 1
fi

case="$srcdir/case-$1"; shift
initfile="$1"; shift

hrecord="./adnstest_record"

case "$1"
in
    -*)
        initflags="$1"; shift
esac

if test "x$1" = "x<"
then
    shift; exec <"$case.in"
fi

case "$1"
in
    =*)
        hrecord="`echo \"$1\" | sed -e 's/^=//'`"; shift
esac

if test ! -f "$hrecord" -a -f "${hrecord}_record"
then
    case "$hrecord"
    in
        /*)
            program="$hrecord"
            ;;

        *)
            program="./$hrecord"
            ;;
    esac
    hrecord="${program}_record"
else
    program="$(echo "$hrecord" | sed -e 's/ .*//; s/_record$//')"
fi

queryargs="$*"
initstring="`cat $srcdir/init-$initfile.text`"
xinitflagsf=$srcdir/$program-xinitflags.text

if test -e $xinitflagsf
then
    useinitflags="$initflags $(cat $xinitflagsf)";
else
    useinitflags="$initflags /"
fi

echo $program $initfile $initflags >"$case.sys"
echo "$queryargs" >>"$case.sys"

EF_DISABLE_BANNER=1
export EF_DISABLE_BANNER

rm -f pipe.out pipe.err
mknod pipe.out p
mknod pipe.err p
tee <pipe.out "$case.out" &
tee_out=$!
tee <pipe.err "$case.err" &
tee_err=$!
exec 4>pipe.out
exec 5>pipe.err

echo running hrecord $initflags "... $queryargs"
set +e
ADNS_TEST_OUT_FD=3 3>>"$case.sys" >&4 2>&5 \
 $hrecord $useinitflags"$initstring" $queryargs
rc=$?
set -e

echo "rc=$rc" >&4
exec 4>&-
exec 5>&-

wait $tee_out
wait $tee_err
echo "exit status: $rc"
